name: CI-Back

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v3

      - name: 자바 설치
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: gradlew 권한 부여
        run: chmod +x gradlew

      - name: Gradle build
        run: ./gradlew build

      - name: 테스트 결과 PR에 커멘트 등록
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'

      - name: 테스트 실패 Check 코멘트 등록
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ github.token }}

      - name: 테스트 실패 시 Merging 방지
        run: |
          # 테스트 결과 XML 파일에서 실패 테스트의 수를 파싱하여 변수에 저장
          failed_tests=$(grep -c "<failure" backend/build/test-results/test/TEST-*.xml || true)

          # 실패 테스트가 있는 경우, Merging을 방지하고 오류 메시지 출력
          if [[ "$failed_tests" -gt 0 ]]; then
            echo "테스트 실패로 인해 Merging이 거부되었습니다."
            exit 1
          fi
