name: Assign Reviewer By Label
on:
  pull_request:
    types:
      - unlabeled
      - labeled
jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: all-label
        id: all-label
        uses: buildsville/assign-reviewer-by-label@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          labels: '[ "ALL" ]'
          reviewers: '["BGuga"]'
          remove-when-no-label: "true"
